### ISSUE TITLE
Error during launch

### ISSUE THREAD

**Issue by ocgltd** [SpiralCut/plugin.program.advanced.launcher#4]
I'm trying to use this plugin but am having trouble understanding the error below (which occurs when I try to open the plugin after installation).  Can someone explain what is wrong / what I need to do to fix this?

```
10:21:29.488 T:140626604425024   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.advanced.launcher/) failed
10:21:29.787 T:140626570565376 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
10:22:04.465 T:140626437261056 WARNING: Previous line repeats 65 times.
10:22:04.465 T:140626437261056   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named requests
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.program.advanced.launcher/addon.py", line 20, in <module>
                                                plugin.Main()
                                              File "/home/kodi/.kodi/addons/plugin.program.advanced.launcher/resources/lib/launcher_plugin.py", line 103, in __init__
                                                self._get_scrapers()
                                              File "/home/kodi/.kodi/addons/plugin.program.advanced.launcher/resources/lib/launcher_plugin.py", line 1658, in _get_scrapers
                                                exec "import resources.scrapers.datas.TheGamesDB.datas_scraper as _data_scraper"
                                              File "<string>", line 1, in <module>
                                              File "/home/kodi/.kodi/addons/plugin.program.advanced.launcher/resources/scrapers/datas/TheGamesDB/datas_scraper.py", line 4, in <module>
                                                import requests
                                            ImportError: No module named requests
                                            -->End of Python script error report<--
10:22:04.507 T:140626450728704   ERROR: GetDirectory - Error getting plugin://plugin.program.advanced.launcher/
10:22:04.521 T:140626604425024   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.advanced.launcher/) failed
10:22:04.688 T:140626570565376 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
10:24:24.317 T:140625963140864 WARNING: Previous line repeats 264 times.

```

**Comment by ocgltd** [comment]
I think the "ImportError: No module named requests" should have 'requests' in quotes...I didn't realize that is the NAME of a module.  So after some searching I was able to add module and problem is solved.  Leaving this up for any other newbees...
